version: '3.8'

services:
  apigateway:
    build:
      context: ./API_Gateway/ApiGateway
      dockerfile: Dockerfile
    ports:
      - "8000:8080"
    env_file:
      - .env

  identityservice:
    build:
      context: ./Services/IdentityService
      dockerfile: Dockerfile
    ports:
      - "8001:8080"
    env_file:
      - .env

  adminservice:
    build:
      context: ./Services/AdminService
      dockerfile: Dockerfile
    ports:
      - "8002:8080"
    env_file:
      - .env

  paperservice:
    build:
      context: ./Services/PaperService
      dockerfile: Dockerfile
    ports:
      - "8003:8080"
    env_file:
      - .env

  trendservice:
    build:
      context: ./Services/TrendService
      dockerfile: Dockerfile
    ports:
      - "8004:8080"
    env_file:
      - .env

  userservice:
    build:
      context: ./Services/UserService
      dockerfile: Dockerfile
    ports:
      - "8005:8080"
    env_file:
      - .env
