// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PaperService.Data;
using PaperService.Entities;

#nullable disable

namespace PaperService.Migrations
{
    [DbContext(typeof(PaperDbContext))]
    [Migration("20260717153542_AddAIResearchGapFeature")]
    partial class AddAIResearchGapFeature
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "keyword_source", new[] { "user", "api" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "paper_source", new[] { "openalex", "semantic_scholar", "crossref" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "sync_status", new[] { "running", "success", "failed", "cancelled" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PaperService.Entities.ApiSyncJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<int>("PapersFetched")
                        .HasColumnType("integer")
                        .HasColumnName("papers_fetched");

                    b.Property<int>("PapersInserted")
                        .HasColumnType("integer")
                        .HasColumnName("papers_inserted");

                    b.Property<int>("PapersUpdated")
                        .HasColumnType("integer")
                        .HasColumnName("papers_updated");

                    b.Property<string>("QueryParams")
                        .HasColumnType("jsonb")
                        .HasColumnName("query_params");

                    b.Property<DateTime?>("ScheduledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_at");

                    b.Property<string>("SourceBaseUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_base_url");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("source_name");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<SyncStatus>("Status")
                        .HasColumnType("sync_status")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("SourceName");

                    b.HasIndex("Status");

                    b.ToTable("api_sync_jobs");
                });

            modelBuilder.Entity("PaperService.Entities.Author", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Affiliation")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("affiliation");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("external_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("Orcid")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("orcid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.HasIndex("Orcid");

                    b.ToTable("authors");
                });

            modelBuilder.Entity("PaperService.Entities.Journal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EIssn")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("e_issn");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("external_id");

                    b.Property<string>("Field")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("field");

                    b.Property<string>("HomepageUrl")
                        .HasColumnType("text")
                        .HasColumnName("homepage_url");

                    b.Property<string>("Issn")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("issn");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("name");

                    b.Property<string>("Publisher")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("publisher");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.ToTable("journals");
                });

            modelBuilder.Entity("PaperService.Entities.Keyword", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("NormalizedTerm")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("normalized_term");

                    b.Property<KeywordSource>("Source")
                        .HasColumnType("keyword_source")
                        .HasColumnName("source");

                    b.Property<string>("Term")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("term");

                    b.Property<int>("UsageCount")
                        .HasColumnType("integer")
                        .HasColumnName("usage_count");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedTerm");

                    b.HasIndex("Term")
                        .IsUnique();

                    b.ToTable("keywords");
                });

            modelBuilder.Entity("PaperService.Entities.Paper", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Abstract")
                        .HasColumnType("text")
                        .HasColumnName("abstract");

                    b.Property<int>("CitationCount")
                        .HasColumnType("integer")
                        .HasColumnName("citation_count");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Doi")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("doi");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("external_id");

                    b.Property<List<string>>("FieldsOfStudy")
                        .HasColumnType("text[]")
                        .HasColumnName("fields_of_study");

                    b.Property<string>("FullText")
                        .HasColumnType("text")
                        .HasColumnName("full_text");

                    b.Property<Guid?>("JournalId")
                        .HasColumnType("uuid")
                        .HasColumnName("journal_id");

                    b.Property<string>("PdfUrl")
                        .HasColumnType("text")
                        .HasColumnName("pdf_url");

                    b.Property<short?>("PublicationYear")
                        .HasColumnType("smallint")
                        .HasColumnName("publication_year");

                    b.Property<string>("RawData")
                        .HasColumnType("jsonb")
                        .HasColumnName("raw_data");

                    b.Property<int>("ReferenceCount")
                        .HasColumnType("integer")
                        .HasColumnName("reference_count");

                    b.Property<PaperSource>("Source")
                        .HasColumnType("paper_source")
                        .HasColumnName("source");

                    b.Property<DateTime>("SyncedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("synced_at");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Url")
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id");

                    b.HasIndex("Doi");

                    b.HasIndex("ExternalId");

                    b.HasIndex("JournalId");

                    b.HasIndex("PublicationYear");

                    b.HasIndex("ExternalId", "Source")
                        .IsUnique();

                    b.ToTable("papers");
                });

            modelBuilder.Entity("PaperService.Entities.PaperAuthor", b =>
                {
                    b.Property<Guid>("PaperId")
                        .HasColumnType("uuid")
                        .HasColumnName("paper_id");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_id");

                    b.Property<short>("AuthorOrder")
                        .HasColumnType("smallint")
                        .HasColumnName("author_order");

                    b.HasKey("PaperId", "AuthorId");

                    b.HasIndex("AuthorId");

                    b.ToTable("paper_authors");
                });

            modelBuilder.Entity("PaperService.Entities.PaperKeyword", b =>
                {
                    b.Property<Guid>("PaperId")
                        .HasColumnType("uuid")
                        .HasColumnName("paper_id");

                    b.Property<Guid>("KeywordId")
                        .HasColumnType("uuid")
                        .HasColumnName("keyword_id");

                    b.Property<double?>("RelevanceScore")
                        .HasColumnType("double precision")
                        .HasColumnName("relevance_score");

                    b.HasKey("PaperId", "KeywordId");

                    b.HasIndex("KeywordId");

                    b.ToTable("paper_keywords");
                });

            modelBuilder.Entity("PaperService.Entities.ResearchMatrix", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("MatrixDataJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("matrix_data");

                    b.Property<string>("PaperIdsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("paper_ids");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("UserIdeaPrompt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_idea_prompt");

                    b.HasKey("Id");

                    b.ToTable("research_matrices");
                });

            modelBuilder.Entity("PaperService.Entities.SyncCursor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("LastCursor")
                        .HasColumnType("text")
                        .HasColumnName("last_cursor");

                    b.Property<DateTime?>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_synced_at");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("source_name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("SourceName")
                        .IsUnique();

                    b.ToTable("sync_cursors");
                });

            modelBuilder.Entity("PaperService.Entities.SyncError", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ErrorDetail")
                        .HasColumnType("text")
                        .HasColumnName("error_detail");

                    b.Property<string>("ErrorType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("error_type");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("external_id");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.ToTable("sync_errors");
                });

            modelBuilder.Entity("PaperService.Entities.Paper", b =>
                {
                    b.HasOne("PaperService.Entities.Journal", "Journal")
                        .WithMany("Papers")
                        .HasForeignKey("JournalId");

                    b.Navigation("Journal");
                });

            modelBuilder.Entity("PaperService.Entities.PaperAuthor", b =>
                {
                    b.HasOne("PaperService.Entities.Author", "Author")
                        .WithMany("PaperAuthors")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PaperService.Entities.Paper", "Paper")
                        .WithMany("PaperAuthors")
                        .HasForeignKey("PaperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Paper");
                });

            modelBuilder.Entity("PaperService.Entities.PaperKeyword", b =>
                {
                    b.HasOne("PaperService.Entities.Keyword", "Keyword")
                        .WithMany("PaperKeywords")
                        .HasForeignKey("KeywordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PaperService.Entities.Paper", "Paper")
                        .WithMany("PaperKeywords")
                        .HasForeignKey("PaperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Keyword");

                    b.Navigation("Paper");
                });

            modelBuilder.Entity("PaperService.Entities.SyncError", b =>
                {
                    b.HasOne("PaperService.Entities.ApiSyncJob", "Job")
                        .WithMany("SyncErrors")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("PaperService.Entities.ApiSyncJob", b =>
                {
                    b.Navigation("SyncErrors");
                });

            modelBuilder.Entity("PaperService.Entities.Author", b =>
                {
                    b.Navigation("PaperAuthors");
                });

            modelBuilder.Entity("PaperService.Entities.Journal", b =>
                {
                    b.Navigation("Papers");
                });

            modelBuilder.Entity("PaperService.Entities.Keyword", b =>
                {
                    b.Navigation("PaperKeywords");
                });

            modelBuilder.Entity("PaperService.Entities.Paper", b =>
                {
                    b.Navigation("PaperAuthors");

                    b.Navigation("PaperKeywords");
                });
#pragma warning restore 612, 618
        }
    }
}
